### ISSUE TITLE
minimum field value of 1, CreateTargetGroupInput.Port

### ISSUE THREAD

**Issue by rs-steve-stevens** [openshift/aws-load-balancer-operator#132]
I have been following this [guide](https://docs.openshift.com/rosa/cloud_experts_tutorials/cloud-experts-aws-load-balancer-operator.html) and subsequently the tutorial.md for this repository in order to create a public ALB in my OpenShift environment (in ROSA).

When I attempt to implement it, I get the following error:
`InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.`

My manifest looks like this:
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  name: public-ingress-static01-test
  namespace: non-prod-apic
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: apic-gw-datapower
                port:
                  number: 9443
```
The examples from both of the openshift tutorial and the tutorial.md do not reference how you change your listener to select a given port. For instance, the intention is to expose 443 on the ALB.
Could you inform me of the change I need to make to specify the targetgroup port, or point me to the documentation for this?

Additionally, I intend to attach a WAF an ACM certificate and Global Accelerator. 
Would I do this using the [standard/upstream annotations](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/)?
